# ECS Fargate service for qontinui-web (FastAPI backend).
#
# Shape mirrors modules/coord. Differences:
#   - Container port 8000 (uvicorn), not 9870.
#   - Reuses the ECS cluster created by modules/coord (passed in as
#     cluster_id) — one cluster per environment.
#   - Reuses the ALB created by modules/tunnel — modules/tunnel's
#     web_target_group input is wired to web's target group ARN by the
#     composition root.
#   - DATABASE_URL points at the SAME canonical Postgres (qontinui_db) as
#     coord. The unified qontinui-web alembic chain has already created
#     coord.* + public.* + auth.* + cloud.*; web reads/writes its own
#     schemas, coord reads/writes coord.*. Per
#     proj_canonical_one_db_unified_alembic — one DB, many schemas, one
#     chain.
#   - REDIS_ENABLED=true. The managed Redis is reached via the canonical
#     REDIS_URL secret (qontinui/<env>/web/redis_url, a rediss:// Upstash
#     DSN carrying scheme/TLS/auth). web's RedisConfig, the ARQ pool
#     (RedisSettings.from_dsn), and the slowapi rate-limiter all honor
#     REDIS_URL (ssl=True for rediss://); startup degrades gracefully to
#     "no task queue" if Redis is briefly unreachable. Redis is required
#     for the runner-WebSocket session store (ws_session_id presence) that
#     drives mobile runner-pairing discovery; with it OFF a paired runner
#     never reports ws_connected. The secret is IAM-granted to the exec
#     role below; it must be both granted AND mounted in the container
#     `secrets` block for the value to reach the app.
#   - COORD_ADMIN_SECRET is the SAME secret value coord uses (passed in
#     from the composition root). Web mints service-tokens at coord via
#     POST /coord/auth/service-token using this shared secret.

variable "environment" { type = string }
variable "region" { type = string }
variable "vpc_id" { type = string }
variable "private_subnet_ids" { type = list(string) }
variable "client_sg_id" { type = string }

variable "cluster_id" {
  type        = string
  description = "ECS cluster ID — reuse coord's cluster (one per environment)."
}
variable "alb_sg_id" {
  type        = string
  description = "ALB security group ID — referenced as source on the ingress rule that opens port 8000 on the client SG (so ALB health checks + traffic can reach the web task)."
}

variable "image_uri" { type = string }
variable "cpu" { type = number }
variable "memory_mb" { type = number }
variable "desired_count" { type = number }

variable "database_url" {
  type        = string
  sensitive   = true
  description = "PostgreSQL DSN. Must be postgresql:// scheme (NOT postgres://) so SQLAlchemy + asyncpg accept it. Composition root converts."
}
variable "coord_url" {
  type        = string
  description = "Base URL of qontinui-coord for the strategy bridge (e.g. https://coord.staging.qontinui.io)."
}
variable "coord_admin_secret" {
  type      = string
  sensitive = true
}
variable "coord_web_service_secret" {
  type      = string
  sensitive = true
  # Same value coord uses. Web verifies the inbound X-Coord-Service-Secret
  # header on the gate-action notification webhook (T3) against this.
}
variable "secret_key" {
  type        = string
  sensitive   = true
  description = "JWT signing secret (>= 32 chars). Generated by composition root."
}
variable "frontend_url" {
  type        = string
  description = "Vercel frontend origin (e.g. https://qontinui.io). Used for absolute links + included in BACKEND_CORS_ORIGINS."
}
variable "backend_url" {
  type        = string
  description = "Public base URL of this web service (e.g. https://web.staging.qontinui.io)."
}
variable "backend_cors_origins" {
  type        = string
  description = "JSON array of CORS-allowed origins. Pydantic parses with json.loads when value starts with '['."
}
variable "backend_cors_origin_regex" {
  type        = string
  default     = ""
  description = "Optional regex pattern for CORS-allowed origins (in addition to backend_cors_origins). An origin matching either the exact list OR this regex is permitted. Decouples backend deploys from frontend domain provisioning — any subdomain matching the pattern works without a task-def revision. Empty string = exact list only."
}

variable "cognito_user_pool_arn" {
  type        = string
  description = "ARN of the (manually-managed, NOT-in-Terraform) Cognito user pool the web task administers for cross-IdP account linking. The web task role is granted admin user-management cognito-idp actions scoped to ONLY this pool ARN. Pool us-east-1_rgTB9dbZ1 lives in us-east-1/047719635665 and is referenced by ARN, never imported."
}

# ─── Security group rule: ALB → web on 8000 ─────────────────────────────
# The shared client_sg only opens port 9870 (coord) from the ALB by default
# — see modules/network/main.tf "client_from_alb_9870". Web listens on
# 8000, so it needs its own ingress rule. Lives in this module (not
# modules/network) so the port + description stay co-located with the
# service that defines them.

resource "aws_security_group_rule" "client_from_alb_8000" {
  type                     = "ingress"
  from_port                = 8000
  to_port                  = 8000
  protocol                 = "tcp"
  source_security_group_id = var.alb_sg_id
  security_group_id        = var.client_sg_id
  description              = "ALB to web task"
}

# ─── Logging ────────────────────────────────────────────────────────────

resource "aws_cloudwatch_log_group" "web" {
  name              = "/ecs/qontinui-${var.environment}/web"
  retention_in_days = 14
}

# ─── Secrets (sensitive env wired via Secrets Manager) ──────────────────

resource "aws_secretsmanager_secret" "database_url" {
  name        = "qontinui/${var.environment}/web/database_url"
  description = "DATABASE_URL for qontinui-web (${var.environment}). Same canonical DB as coord; different schemas (public/auth/agent/cloud vs coord)."
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id     = aws_secretsmanager_secret.database_url.id
  secret_string = var.database_url
}

resource "aws_secretsmanager_secret" "coord_admin_secret" {
  name        = "qontinui/${var.environment}/web/coord_admin_secret"
  description = "Shared admin secret for the web→coord strategy bridge (${var.environment}). Same value as coord/admin_secret; duplicated here so the web task-exec role doesn't need cross-module IAM grants."
}

resource "aws_secretsmanager_secret_version" "coord_admin_secret" {
  secret_id     = aws_secretsmanager_secret.coord_admin_secret.id
  secret_string = var.coord_admin_secret
}

resource "aws_secretsmanager_secret" "coord_web_service_secret" {
  name        = "qontinui/${var.environment}/web/coord_web_service_secret"
  description = "Shared secret for the coord→web gate-action notification webhook (${var.environment}). Same value as coord/web_service_secret; duplicated here so the web task-exec role doesn't need cross-module IAM grants."
}

resource "aws_secretsmanager_secret_version" "coord_web_service_secret" {
  secret_id     = aws_secretsmanager_secret.coord_web_service_secret.id
  secret_string = var.coord_web_service_secret
}

resource "aws_secretsmanager_secret" "secret_key" {
  name        = "qontinui/${var.environment}/web/secret_key"
  description = "JWT signing secret for qontinui-web (${var.environment})."
}

resource "aws_secretsmanager_secret_version" "secret_key" {
  secret_id     = aws_secretsmanager_secret.secret_key.id
  secret_string = var.secret_key
}

# ─── IAM ────────────────────────────────────────────────────────────────

data "aws_iam_policy_document" "ecs_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ecs-tasks.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "task_exec" {
  name               = "qontinui-${var.environment}-web-exec"
  assume_role_policy = data.aws_iam_policy_document.ecs_assume.json
}

resource "aws_iam_role_policy_attachment" "task_exec_managed" {
  role       = aws_iam_role.task_exec.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

# redis_url secret was created out-of-band (not TF-managed); reference by name
# so the exec-role grant below survives `terraform apply`.
data "aws_secretsmanager_secret" "redis_url" {
  name = "qontinui/${var.environment}/web/redis_url"
}

data "aws_iam_policy_document" "task_exec_secrets" {
  statement {
    actions = ["secretsmanager:GetSecretValue"]
    resources = [
      aws_secretsmanager_secret.database_url.arn,
      aws_secretsmanager_secret.coord_admin_secret.arn,
      aws_secretsmanager_secret.coord_web_service_secret.arn,
      aws_secretsmanager_secret.secret_key.arn,
      data.aws_secretsmanager_secret.redis_url.arn,
    ]
  }
}

resource "aws_iam_role_policy" "task_exec_secrets" {
  role   = aws_iam_role.task_exec.id
  policy = data.aws_iam_policy_document.task_exec_secrets.json
}

# Task role: web has no S3/SES/SQS needs at staging (cloud-control's Stripe
# + SES paths are off until billing/email is wired). Carries ONLY the
# cross-IdP account-linking grant below; extend when storage/email backends
# move to AWS-native.
resource "aws_iam_role" "task" {
  name               = "qontinui-${var.environment}-web-task"
  assume_role_policy = data.aws_iam_policy_document.ecs_assume.json
}

# Cross-IdP account-linking admin grant. The web backend reconciles federated
# identities (Google / Microsoft Entra / GitHub) against the native Cognito
# user when a user explicitly links/unlinks an IdP from the account-settings
# UI, and resolves/cleans up users during that flow. Deliberately a SEPARATE,
# narrow, auditable policy (same rationale as coord's task_blob /
# task_session_output_cold) — Resource is scoped to ONLY the one pool ARN
# (passed in from the composition root; pool is manually managed and NOT in
# Terraform, referenced by ARN). admin_link_provider_for_user is the one
# privileged action; the rest are read/disable/delete used by the same flow.
# (PreSignUp *auto*-link runs in its own Lambda with its own role — see
# modules/cross-idp-linking — not under this task role.)
data "aws_iam_policy_document" "task_cognito_linking" {
  statement {
    sid = "CognitoCrossIdpAccountLinking"
    actions = [
      "cognito-idp:AdminLinkProviderForUser",
      "cognito-idp:AdminDisableProviderForUser",
      "cognito-idp:AdminGetUser",
      "cognito-idp:AdminDeleteUser",
      "cognito-idp:ListUsers",
    ]
    resources = [var.cognito_user_pool_arn]
  }

  # Group-admin grant. The web backend manages Cognito groups (org/role
  # membership) — create/list/delete groups, enumerate users in a group, and
  # add/remove a user to/from a group. Same pool ARN scope as the linking
  # statement above; kept as a SEPARATE statement so the group-admin surface
  # is independently auditable from the cross-IdP linking surface.
  statement {
    sid = "CognitoGroupAdmin"
    actions = [
      "cognito-idp:CreateGroup",
      "cognito-idp:DeleteGroup",
      "cognito-idp:GetGroup",
      "cognito-idp:ListGroups",
      "cognito-idp:ListUsersInGroup",
      "cognito-idp:AdminAddUserToGroup",
      "cognito-idp:AdminRemoveUserFromGroup",
    ]
    resources = [var.cognito_user_pool_arn]
  }
}

resource "aws_iam_role_policy" "task_cognito_linking" {
  name   = "qontinui-${var.environment}-web-cognito-linking"
  role   = aws_iam_role.task.id
  policy = data.aws_iam_policy_document.task_cognito_linking.json
}

# ECS Exec (SSM Session Manager) — mirrors modules/coord's task_ecs_exec.
# `enable_execute_command = true` is already set on aws_ecs_service.web
# (below), but exec ALSO needs these ssmmessages channel actions on the TASK
# role. Without them the ExecuteCommandAgent starts (ECS reports the managed
# agent `RUNNING`) yet the SSM control plane can never open its channel, so
# every `aws ecs execute-command` into web fails `TargetNotConnected` — which
# it did, permanently, until this was added. coord carried the identical
# policy and worked; web did not and never has. The actions have no
# resource-level scoping, so `resources = ["*"]` is required.
#
# Why web specifically needs it: web is the only container with `python` +
# `psycopg2` + `DATABASE_URL`, so it is the sanctioned place to run one-off
# read-only SQL against the VPC-internal RDS. coord's image is curl-only.
#
# This closes a real workaround hazard: with exec dead, the fallback is
# `aws ecs run-task --overrides command=[...]`, which is safe on web (no
# image ENTRYPOINT) but is NOT a general substitute — the same trick against
# coord cannot override its `/app/qontinui-coord` ENTRYPOINT and boots a
# lease-holding server (four orphaned tasks caused the 2026-06-30 leaderless
# outage). Restoring exec on web removes the temptation to generalize it.
data "aws_iam_policy_document" "task_ecs_exec" {
  statement {
    sid = "EcsExecSsmMessages"
    actions = [
      "ssmmessages:CreateControlChannel",
      "ssmmessages:CreateDataChannel",
      "ssmmessages:OpenControlChannel",
      "ssmmessages:OpenDataChannel",
    ]
    resources = ["*"]
  }
}

resource "aws_iam_role_policy" "task_ecs_exec" {
  name   = "ecs-exec-ssmmessages"
  role   = aws_iam_role.task.id
  policy = data.aws_iam_policy_document.task_ecs_exec.json
}

# ─── Task definition ────────────────────────────────────────────────────

resource "aws_ecs_task_definition" "web" {
  family                   = "qontinui-${var.environment}-web"
  cpu                      = var.cpu
  memory                   = var.memory_mb
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  execution_role_arn       = aws_iam_role.task_exec.arn
  task_role_arn            = aws_iam_role.task.arn

  runtime_platform {
    operating_system_family = "LINUX"
    cpu_architecture        = "X86_64"
  }

  container_definitions = jsonencode([
    {
      name      = "web"
      image     = var.image_uri
      essential = true

      portMappings = [{
        containerPort = 8000
        hostPort      = 8000
        protocol      = "tcp"
      }]

      environment = [
        { name = "ENVIRONMENT", value = var.environment },
        { name = "DEBUG", value = "false" },
        { name = "RELOAD", value = "false" },
        { name = "HOST", value = "0.0.0.0" },
        { name = "PORT", value = "8000" },
        { name = "COORD_URL", value = var.coord_url },
        { name = "FRONTEND_URL", value = var.frontend_url },
        { name = "BACKEND_URL", value = var.backend_url },
        { name = "BACKEND_CORS_ORIGINS", value = var.backend_cors_origins },
        { name = "BACKEND_CORS_ORIGIN_REGEX", value = var.backend_cors_origin_regex },
        { name = "REDIS_ENABLED", value = "true" },
        { name = "RATE_LIMIT_ENABLED", value = "true" },
        { name = "USE_SES_API", value = "false" },
        # Storage: local-filesystem-in-container for staging. Persists for the
        # container's lifetime; resets on task replacement. S3 is the future
        # direction; not blocking for two-account Strategy smoke.
        { name = "STORAGE_BACKEND", value = "local" },
      ]

      secrets = [
        { name = "DATABASE_URL", valueFrom = aws_secretsmanager_secret.database_url.arn },
        { name = "COORD_ADMIN_SECRET", valueFrom = aws_secretsmanager_secret.coord_admin_secret.arn },
        # Inbound gate-action webhook auth (T3). NOTE: the web service
        # `ignore_changes`s its task_definition (deploys clone the live def +
        # swap the image), so this bootstrap-def entry is for parity only — the
        # running mount is added to the live task def at activation time.
        { name = "COORD_WEB_SERVICE_SECRET", valueFrom = aws_secretsmanager_secret.coord_web_service_secret.arn },
        { name = "SECRET_KEY", valueFrom = aws_secretsmanager_secret.secret_key.arn },
        # REDIS_URL (rediss:// Upstash DSN) — the exec role is already granted
        # GetSecretValue on this secret above; mounting it here is what makes
        # the value reach the container so REDIS_ENABLED=true can connect.
        { name = "REDIS_URL", valueFrom = data.aws_secretsmanager_secret.redis_url.arn },
      ]

      logConfiguration = {
        logDriver = "awslogs"
        options = {
          "awslogs-group"         = aws_cloudwatch_log_group.web.name
          "awslogs-region"        = var.region
          "awslogs-stream-prefix" = "web"
        }
      }

      healthCheck = {
        command     = ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/health/live', timeout=5)\" || exit 1"]
        interval    = 30
        timeout     = 10
        retries     = 3
        startPeriod = 60
      }
    }
  ])
}

# ─── Target group + service ─────────────────────────────────────────────

resource "aws_lb_target_group" "web" {
  name        = "qontinui-${var.environment}-web"
  port        = 8000
  protocol    = "HTTP"
  vpc_id      = var.vpc_id
  target_type = "ip"

  health_check {
    enabled             = true
    path                = "/api/v1/health/live"
    port                = "8000"
    protocol            = "HTTP"
    interval            = 30
    timeout             = 10
    healthy_threshold   = 2
    unhealthy_threshold = 3
    matcher             = "200"
  }

  deregistration_delay = 30
}

resource "aws_ecs_service" "web" {
  name            = "web"
  cluster         = var.cluster_id
  task_definition = aws_ecs_task_definition.web.arn
  desired_count   = var.desired_count
  launch_type     = "FARGATE"

  network_configuration {
    subnets          = var.private_subnet_ids
    security_groups  = [var.client_sg_id]
    assign_public_ip = false
  }

  load_balancer {
    target_group_arn = aws_lb_target_group.web.arn
    container_name   = "web"
    container_port   = 8000
  }

  deployment_minimum_healthy_percent = 50
  deployment_maximum_percent         = 200

  # Auto-roll-back a failed deploy instead of leaving the service flapping on a
  # crash-looping task. Enabled live 2026-05-24 during the web image crash-loop
  # incident (a stale-schemas image boot-failed ~30x over an hour because the
  # breaker was off); codified here so `terraform apply` stops planning to
  # disable it. CI (staging-web-deploy.yml) relies on this backstop plus its
  # post-deploy verify step that fails loudly if a rollback occurs.
  deployment_circuit_breaker {
    enable   = true
    rollback = true
  }

  enable_execute_command = true

  # TF/CI seam. Terraform owns the canonical task-def DEFINITION
  # (aws_ecs_task_definition.web above: cpu/memory/env/secrets/health/IAM/log)
  # and all provisioning. CI (qontinui-web/.github/workflows/staging-web-deploy.yml)
  # owns DEPLOYMENT: it `describe-task-definition`s THIS family's latest revision
  # (inheriting the canonical definition here), swaps in the freshly-built
  # SHA-pinned image, registers a new revision, and points the service at it.
  # So Terraform must NOT revert the service's task_definition pointer to its
  # own revision — that would undo every CI deploy and fight the pipeline.
  # The canonical definition stays live because CI inherits it via describe-latest;
  # Terraform-side task-def changes (e.g. memory, a new secret) take effect on the
  # next CI deploy. desired_count is owned by autoscaling / stop-start scripts
  # (same rationale as module.coord). Deployment is agent-driven (CI); `terraform
  # apply` stays a human-gated provisioning op that never touches the running revision.
  lifecycle {
    ignore_changes = [task_definition, desired_count]
  }

  depends_on = [aws_lb_target_group.web]
}

# ─── Outputs ────────────────────────────────────────────────────────────

output "service_name" { value = aws_ecs_service.web.name }
output "target_group_arn" { value = aws_lb_target_group.web.arn }
output "target_group_arn_suffix" { value = aws_lb_target_group.web.arn_suffix }
output "task_exec_role_arn" { value = aws_iam_role.task_exec.arn }
output "task_role_arn" { value = aws_iam_role.task.arn }
output "log_group_name" { value = aws_cloudwatch_log_group.web.name }
