# ECS Fargate service for qontinui-web (FastAPI backend).
#
# Shape mirrors modules/coord. Differences:
#   - Container port 8000 (uvicorn), not 9870.
#   - Reuses the ECS cluster created by modules/coord (passed in as
#     cluster_id) — one cluster per environment.
#   - Reuses the ALB created by modules/tunnel — modules/tunnel's
#     web_target_group input is wired to web's target group ARN by the
#     composition root.
#   - DATABASE_URL points at the SAME canonical Postgres (qontinui_db) as
#     coord. The unified qontinui-web alembic chain has already created
#     coord.* + public.* + auth.* + cloud.*; web reads/writes its own
#     schemas, coord reads/writes coord.*. Per
#     proj_canonical_one_db_unified_alembic — one DB, many schemas, one
#     chain.
#   - REDIS_ENABLED defaults to false. ElastiCache requires TLS + auth
#     token; web's RedisConfig (app/config/redis_config.py) builds plain
#     redis://HOST:PORT/DB without TLS or password support. Optional
#     redis-dependent features (ARQ task queue, connection cleanup,
#     redbeat scheduler) gracefully no-op when disabled. Re-enable when
#     web supports rediss:// or REDIS_URL.
#   - COORD_ADMIN_SECRET is the SAME secret value coord uses (passed in
#     from the composition root). Web mints service-tokens at coord via
#     POST /coord/auth/service-token using this shared secret.

variable "environment" { type = string }
variable "region" { type = string }
variable "vpc_id" { type = string }
variable "private_subnet_ids" { type = list(string) }
variable "client_sg_id" { type = string }

variable "cluster_id" {
  type        = string
  description = "ECS cluster ID — reuse coord's cluster (one per environment)."
}
variable "alb_sg_id" {
  type        = string
  description = "ALB security group ID — referenced as source on the ingress rule that opens port 8000 on the client SG (so ALB health checks + traffic can reach the web task)."
}

variable "image_uri" { type = string }
variable "cpu" { type = number }
variable "memory_mb" { type = number }
variable "desired_count" { type = number }

variable "database_url" {
  type        = string
  sensitive   = true
  description = "PostgreSQL DSN. Must be postgresql:// scheme (NOT postgres://) so SQLAlchemy + asyncpg accept it. Composition root converts."
}
variable "coord_url" {
  type        = string
  description = "Base URL of qontinui-coord for the strategy bridge (e.g. https://coord.staging.qontinui.io)."
}
variable "coord_admin_secret" {
  type      = string
  sensitive = true
}
variable "secret_key" {
  type        = string
  sensitive   = true
  description = "JWT signing secret (>= 32 chars). Generated by composition root."
}
variable "frontend_url" {
  type        = string
  description = "Vercel frontend origin (e.g. https://qontinui.io). Used for absolute links + included in BACKEND_CORS_ORIGINS."
}
variable "backend_url" {
  type        = string
  description = "Public base URL of this web service (e.g. https://web.staging.qontinui.io)."
}
variable "backend_cors_origins" {
  type        = string
  description = "JSON array of CORS-allowed origins. Pydantic parses with json.loads when value starts with '['."
}
variable "backend_cors_origin_regex" {
  type        = string
  default     = ""
  description = "Optional regex pattern for CORS-allowed origins (in addition to backend_cors_origins). An origin matching either the exact list OR this regex is permitted. Decouples backend deploys from frontend domain provisioning — any subdomain matching the pattern works without a task-def revision. Empty string = exact list only."
}

# ─── Security group rule: ALB → web on 8000 ─────────────────────────────
# The shared client_sg only opens port 9870 (coord) from the ALB by default
# — see modules/network/main.tf "client_from_alb_9870". Web listens on
# 8000, so it needs its own ingress rule. Lives in this module (not
# modules/network) so the port + description stay co-located with the
# service that defines them.

resource "aws_security_group_rule" "client_from_alb_8000" {
  type                     = "ingress"
  from_port                = 8000
  to_port                  = 8000
  protocol                 = "tcp"
  source_security_group_id = var.alb_sg_id
  security_group_id        = var.client_sg_id
  description              = "ALB to web task"
}

# ─── Logging ────────────────────────────────────────────────────────────

resource "aws_cloudwatch_log_group" "web" {
  name              = "/ecs/qontinui-${var.environment}/web"
  retention_in_days = 14
}

# ─── Secrets (sensitive env wired via Secrets Manager) ──────────────────

resource "aws_secretsmanager_secret" "database_url" {
  name        = "qontinui/${var.environment}/web/database_url"
  description = "DATABASE_URL for qontinui-web (${var.environment}). Same canonical DB as coord; different schemas (public/auth/agent/cloud vs coord)."
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id     = aws_secretsmanager_secret.database_url.id
  secret_string = var.database_url
}

resource "aws_secretsmanager_secret" "coord_admin_secret" {
  name        = "qontinui/${var.environment}/web/coord_admin_secret"
  description = "Shared admin secret for the web→coord strategy bridge (${var.environment}). Same value as coord/admin_secret; duplicated here so the web task-exec role doesn't need cross-module IAM grants."
}

resource "aws_secretsmanager_secret_version" "coord_admin_secret" {
  secret_id     = aws_secretsmanager_secret.coord_admin_secret.id
  secret_string = var.coord_admin_secret
}

resource "aws_secretsmanager_secret" "secret_key" {
  name        = "qontinui/${var.environment}/web/secret_key"
  description = "JWT signing secret for qontinui-web (${var.environment})."
}

resource "aws_secretsmanager_secret_version" "secret_key" {
  secret_id     = aws_secretsmanager_secret.secret_key.id
  secret_string = var.secret_key
}

# ─── IAM ────────────────────────────────────────────────────────────────

data "aws_iam_policy_document" "ecs_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ecs-tasks.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "task_exec" {
  name               = "qontinui-${var.environment}-web-exec"
  assume_role_policy = data.aws_iam_policy_document.ecs_assume.json
}

resource "aws_iam_role_policy_attachment" "task_exec_managed" {
  role       = aws_iam_role.task_exec.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

data "aws_iam_policy_document" "task_exec_secrets" {
  statement {
    actions = ["secretsmanager:GetSecretValue"]
    resources = [
      aws_secretsmanager_secret.database_url.arn,
      aws_secretsmanager_secret.coord_admin_secret.arn,
      aws_secretsmanager_secret.secret_key.arn,
    ]
  }
}

resource "aws_iam_role_policy" "task_exec_secrets" {
  role   = aws_iam_role.task_exec.id
  policy = data.aws_iam_policy_document.task_exec_secrets.json
}

# Task role: web has no S3/SES/SQS needs at staging (cloud-control's Stripe
# + SES paths are off until billing/email is wired). Keep empty for now;
# extend when storage/email backends move to AWS-native.
resource "aws_iam_role" "task" {
  name               = "qontinui-${var.environment}-web-task"
  assume_role_policy = data.aws_iam_policy_document.ecs_assume.json
}

# ─── Task definition ────────────────────────────────────────────────────

resource "aws_ecs_task_definition" "web" {
  family                   = "qontinui-${var.environment}-web"
  cpu                      = var.cpu
  memory                   = var.memory_mb
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  execution_role_arn       = aws_iam_role.task_exec.arn
  task_role_arn            = aws_iam_role.task.arn

  runtime_platform {
    operating_system_family = "LINUX"
    cpu_architecture        = "X86_64"
  }

  container_definitions = jsonencode([
    {
      name      = "web"
      image     = var.image_uri
      essential = true

      portMappings = [{
        containerPort = 8000
        hostPort      = 8000
        protocol      = "tcp"
      }]

      environment = [
        { name = "ENVIRONMENT", value = var.environment },
        { name = "DEBUG", value = "false" },
        { name = "RELOAD", value = "false" },
        { name = "HOST", value = "0.0.0.0" },
        { name = "PORT", value = "8000" },
        { name = "COORD_URL", value = var.coord_url },
        { name = "FRONTEND_URL", value = var.frontend_url },
        { name = "BACKEND_URL", value = var.backend_url },
        { name = "BACKEND_CORS_ORIGINS", value = var.backend_cors_origins },
        { name = "BACKEND_CORS_ORIGIN_REGEX", value = var.backend_cors_origin_regex },
        { name = "REDIS_ENABLED", value = "false" },
        { name = "RATE_LIMIT_ENABLED", value = "true" },
        { name = "USE_SES_API", value = "false" },
        # Storage: local-filesystem-in-container for staging. Persists for the
        # container's lifetime; resets on task replacement. S3 is the future
        # direction; not blocking for two-account Strategy smoke.
        { name = "STORAGE_BACKEND", value = "local" },
      ]

      secrets = [
        { name = "DATABASE_URL", valueFrom = aws_secretsmanager_secret.database_url.arn },
        { name = "COORD_ADMIN_SECRET", valueFrom = aws_secretsmanager_secret.coord_admin_secret.arn },
        { name = "SECRET_KEY", valueFrom = aws_secretsmanager_secret.secret_key.arn },
      ]

      logConfiguration = {
        logDriver = "awslogs"
        options = {
          "awslogs-group"         = aws_cloudwatch_log_group.web.name
          "awslogs-region"        = var.region
          "awslogs-stream-prefix" = "web"
        }
      }

      healthCheck = {
        command     = ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/health/live', timeout=5)\" || exit 1"]
        interval    = 30
        timeout     = 10
        retries     = 3
        startPeriod = 60
      }
    }
  ])
}

# ─── Target group + service ─────────────────────────────────────────────

resource "aws_lb_target_group" "web" {
  name        = "qontinui-${var.environment}-web"
  port        = 8000
  protocol    = "HTTP"
  vpc_id      = var.vpc_id
  target_type = "ip"

  health_check {
    enabled             = true
    path                = "/api/v1/health/live"
    port                = "8000"
    protocol            = "HTTP"
    interval            = 30
    timeout             = 10
    healthy_threshold   = 2
    unhealthy_threshold = 3
    matcher             = "200"
  }

  deregistration_delay = 30
}

resource "aws_ecs_service" "web" {
  name            = "web"
  cluster         = var.cluster_id
  task_definition = aws_ecs_task_definition.web.arn
  desired_count   = var.desired_count
  launch_type     = "FARGATE"

  network_configuration {
    subnets          = var.private_subnet_ids
    security_groups  = [var.client_sg_id]
    assign_public_ip = false
  }

  load_balancer {
    target_group_arn = aws_lb_target_group.web.arn
    container_name   = "web"
    container_port   = 8000
  }

  deployment_minimum_healthy_percent = 50
  deployment_maximum_percent         = 200

  enable_execute_command = true

  # TF/CI seam. Terraform owns the canonical task-def DEFINITION
  # (aws_ecs_task_definition.web above: cpu/memory/env/secrets/health/IAM/log)
  # and all provisioning. CI (qontinui-web/.github/workflows/staging-web-deploy.yml)
  # owns DEPLOYMENT: it `describe-task-definition`s THIS family's latest revision
  # (inheriting the canonical definition here), swaps in the freshly-built
  # SHA-pinned image, registers a new revision, and points the service at it.
  # So Terraform must NOT revert the service's task_definition pointer to its
  # own revision — that would undo every CI deploy and fight the pipeline.
  # The canonical definition stays live because CI inherits it via describe-latest;
  # Terraform-side task-def changes (e.g. memory, a new secret) take effect on the
  # next CI deploy. desired_count is owned by autoscaling / stop-start scripts
  # (same rationale as module.coord). Deployment is agent-driven (CI); `terraform
  # apply` stays a human-gated provisioning op that never touches the running revision.
  lifecycle {
    ignore_changes = [task_definition, desired_count]
  }

  depends_on = [aws_lb_target_group.web]
}

# ─── Outputs ────────────────────────────────────────────────────────────

output "service_name" { value = aws_ecs_service.web.name }
output "target_group_arn" { value = aws_lb_target_group.web.arn }
output "target_group_arn_suffix" { value = aws_lb_target_group.web.arn_suffix }
output "task_exec_role_arn" { value = aws_iam_role.task_exec.arn }
output "task_role_arn" { value = aws_iam_role.task.arn }
output "log_group_name" { value = aws_cloudwatch_log_group.web.name }
